# Generated by Django 4.0.5 on 2022-06-26 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(default='', max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
